on:
  push:
    branches:
    - $default-branch
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
        - mainline
        - stable
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        IMAGE_NAME="bcinteractive/nginx"
        VCS_REF="$(git rev-parse --short HEAD)"
        DOCKER_BUILDKIT=1 docker build \
          --build-arg "BUILD_DATE=${BUILD_DATE}" \
          --build-arg "VCS_REF=${VCS_REF}" \
          --tag "${IMAGE_NAME}:${VCS_REF}" \
          --file "${{ matrix.branch}}/Dockerfile" \
          .
        IMAGE_TAG=$(docker image inspect --format='{{ index .Config.Labels "org.opencontainers.image.version"}}' "${IMAGE_NAME}:${VCS_REF}")
        docker push "${IMAGE_NAME}:${IMAGE_TAG}"
